from __future__ import annotations

import re

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db import models, repositories
from app.services.rag import rag_service

SUPPORTED_SYSTEMS = {"Coupa", "SAP", "ServiceNow", "Vendor Master Data", "Payment System", "Policy Repository", "Invoice Management System"}


def run_action(session: Session, action_id: str) -> dict:
    action = session.get(models.ImprovementAction, action_id)
    if action is None:
        raise ValueError("Action not found")
    if action.approval_status != "approved":
        raise PermissionError("Action is not approved")
    if action.target_system not in SUPPORTED_SYSTEMS:
        raise ValueError("Target system schema is missing")

    run = models.AgentRun(action_id=action.id, status="running")
    session.add(run)
    session.flush()
    repositories.create_agent_step(session, run.id, 1, "Load approved action", "completed", {"action_id": action.id}, action_payload(action), "Loaded action and proposal metadata.")
    repositories.create_agent_step(session, run.id, 2, "Check approval", "completed", {"approval_status": action.approval_status}, {"approved_by": action.approved_by}, "Confirmed human approval.")
    context = rag_service.search(session, action.title, top_k=3, filters={"source_type": ["SOP", "POLICY"]})
    repositories.create_agent_step(session, run.id, 3, "Retrieve policy and SOP context", "completed", {"query": action.title}, {"chunks": context}, "Retrieved governed context for mock config generation.")
    config = generate_config(action, context)
    repositories.create_agent_step(session, run.id, 4, "Generate mock target-system config JSON", "completed", action_payload(action), config, "Generated mock configuration. No real external API was called.")
    validation = validate_config(action.target_system, config)
    status = "completed" if validation["valid"] else "failed"
    repositories.create_agent_step(session, run.id, 5, "Validate config JSON", status, config, validation, "Validated required safety fields and schema.")
    if not validation["valid"]:
        run.status = "failed"
        run.validation_result = validation
        run.config_json = config
        session.commit()
        return run_payload(session, run.id)

    stored = models.MockSystemConfig(
        agent_run_id=run.id,
        action_id=action.id,
        target_system=action.target_system,
        configuration_type=config["configuration_type"],
        config_json=config,
        validation_result=validation,
        enabled=config["enabled"],
        requires_final_human_enablement=config["requires_final_human_enablement"],
    )
    session.add(stored)
    repositories.create_agent_step(session, run.id, 6, "Store config", "completed", {"target_system": action.target_system}, {"mock_system_config_id": stored.id}, "Stored generated mock system configuration.")
    run.status = "completed"
    run.validation_result = validation
    run.config_json = config
    repositories.create_agent_step(session, run.id, 7, "Complete run", "completed", {}, {"status": "completed"}, "Agent run completed with auditable mock output.")
    session.commit()
    return run_payload(session, run.id)


def generate_config(action: models.ImprovementAction, context: list[dict]) -> dict:
    rule_name = re.sub(r"[^A-Z0-9]+", "_", action.title.upper()).strip("_")
    base = {
        "system": action.target_system,
        "configuration_type": config_type(action),
        "rule_name": rule_name[:80],
        "enabled": False,
        "requires_final_human_enablement": True,
        "conditions": {
            "approval_status": {"operator": "=", "value": "approved"},
            "duplicate_invoice_check": {"operator": "=", "value": "passed"},
        },
        "actions": [{"type": "add_audit_note", "value": "Generated by approved process improvement mock agent."}],
        "fallback": {"on_condition_fail": "route_to_AP_manual_review", "on_validation_error": "create_ServiceNow_ticket"},
        "audit": {"log_rule_id": True, "log_input_values": True, "log_policy_reference": True},
        "validation_notes": ["Generated from approved action only.", f"Retrieved context chunks: {len(context)}"],
        "cannot_execute_reasons": [],
    }
    if "price mismatch" in action.title.lower():
        base["conditions"].update(
            {
                "invoice_amount": {"operator": "<", "value": 1000, "currency": "EUR"},
                "price_mismatch_percent": {"operator": "<=", "value": 1.5},
                "vendor_risk": {"operator": "=", "value": "low"},
                "goods_receipt_exists": {"operator": "=", "value": True},
                "compliance_block": {"operator": "=", "value": False},
            }
        )
        base["actions"].extend(
            [
                {"type": "set_exception_status", "value": "auto_resolved"},
                {"type": "route_to_payment_scheduling"},
            ]
        )
    if action.target_system == "ServiceNow":
        base["configuration_type"] = "ticket_escalation_rule"
        base["conditions"].update({"ticket_age_business_days": {"operator": ">", "value": 3}})
        base["actions"].append({"type": "escalate_to_queue", "value": "AP Team Lead"})
    if action.target_system == "Policy Repository":
        base["configuration_type"] = "policy_update"
        base["actions"].append({"type": "publish_policy_change", "value": "manual_workaround_prohibition"})
    if action.target_system == "Invoice Management System":
        base["configuration_type"] = "invoice_guidance_rule"
        base["actions"].append({"type": "create_review_guidance", "value": "PO exception review guidance"})
    return base


def config_type(action: models.ImprovementAction) -> str:
    if action.target_system == "Coupa":
        return "invoice_exception_rule"
    if action.target_system == "SAP":
        return "finance_control_rule"
    if action.target_system == "Payment System":
        return "payment_control_rule"
    if action.target_system == "Vendor Master Data":
        return "vendor_risk_rule"
    if action.target_system == "Invoice Management System":
        return "invoice_guidance_rule"
    return "workflow_rule"


def validate_config(target_system: str, config: dict) -> dict:
    errors = []
    required = ["system", "configuration_type", "rule_name", "enabled", "requires_final_human_enablement", "conditions", "actions", "fallback", "audit"]
    for field in required:
        if field not in config:
            errors.append(f"Missing {field}")
    if config.get("system") != target_system:
        errors.append("System mismatch")
    if config.get("enabled") is not False:
        errors.append("enabled must be false")
    if config.get("requires_final_human_enablement") is not True:
        errors.append("requires_final_human_enablement must be true")
    if not config.get("fallback"):
        errors.append("fallback is required")
    if not config.get("audit", {}).get("log_policy_reference"):
        errors.append("audit.log_policy_reference is required")
    return {"valid": not errors, "errors": errors, "schema": target_system}


def run_payload(session: Session, run_id: str) -> dict:
    run = session.get(models.AgentRun, run_id)
    steps = list(session.scalars(select(models.AgentStep).where(models.AgentStep.agent_run_id == run_id).order_by(models.AgentStep.step_order)).all())
    return {
        "id": run.id,
        "action_id": run.action_id,
        "status": run.status,
        "validation_result": run.validation_result,
        "config_json": run.config_json,
        "created_at": run.created_at.isoformat(),
        "steps": [
            {
                "id": step.id,
                "step_order": step.step_order,
                "name": step.name,
                "status": step.status,
                "input_json": step.input_json,
                "output_json": step.output_json,
                "explanation": step.explanation,
            }
            for step in steps
        ],
    }


def action_payload(action: models.ImprovementAction) -> dict:
    return {
        "id": action.id,
        "title": action.title,
        "target_system": action.target_system,
        "action_type": action.action_type,
        "description": action.description,
        "approval_status": action.approval_status,
        "approved_by": action.approved_by,
    }
